[package]
name = "wasmarking"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
ark-std = { version = "^0.3.0", default-features = false }
ark-serialize = { version = "^0.3.0", default-features = false }
ark-bls12-381 = { version = "^0.3.0", default-features = false }
ark-groth16 = { version = "^0.3.0", default-features = false }
ark-snark = { version = "^0.3.0", default-features = false }
instant = { version = "0.1.12", default-features = false, features = [ "wasm-bindgen" ] }
web-sys = { version = "0.3.60", default-features = false, features = ["console"] }
wasm-bindgen = { version = "0.2.83" }

relations = { git = "https://github.com/Cardinal-Cryptography/aleph-node", package = "liminal-ark-relations", default-features = false, features = ["circuit"]}

[dev-dependencies]
criterion = "0.3"
wasm-bindgen-test = { version = "0.3.33", default-features = false }

[[bench]]
name = "withdraw"
harness = false
